### PR TITLE
Add draftable CLI command

### PR DESCRIPTION
**Pull request by casperdcl**
- create `draftable` console script
- documentation

### CODE REVIEW

**Comment by casperdcl** [comment]
looks like this was actually replaced/closed by ee8ff9c on 2018-09-11. The current `dr-compare` command provided by 1004ed6 should ideally be mentioned in the readme...

**Comment by ralish** [comment]
@casperdcl You're quite right and apologies for letting this PR get away from us. I'll get the README updated.

**Comment by ralish** [comment]
Have added some brief documentation to the README: [CLI usage](https://github.com/draftable/compare-api-python-client#cli-usage)

**Comment by casperdcl** [comment]
P.S. doesn't seem to be working (maybe for a different issue; doesn't seem like you use GH issues much though)...

```
$ dr-compare all
Traceback (most recent call last):
  File ".../bin/dr-compare", line 8, in <module>
    sys.exit(dr_compare_main())
  File ".../lib/python2.7/site-packages/draftable/commands/dr_compare.py", line 491, in dr_compare_main
    command(system_args[2:], arg_parser.prog, command_name)
TypeError: list_all_comparisons() takes exactly 1 argument (3 given)
```

**Comment by ralish** [comment]
@casperdcl Thanks for letting us know! We've pushed a fix and published it in the new v1.1.3 release :-)

**Pull request closed without merging**
